include:
  - board: nice_nano/nrf52840/zmk
    shield: jorne_dongle
  - board: nice_nano/nrf52840/zmk
    shield: jorne_left
  - board: nice_nano/nrf52840/zmk
    shield: jorne_right
  - board: nice_nano/nrf52840/zmk
    shield: jorne_dongle
    extra_kconfig: CONFIG_ZMK_SETTINGS_RESET_ON_BOOT=y
  - board: nice_nano/nrf52840/zmk
    shield: settings_reset
