# Отключаем глубокий сон для донгла
CONFIG_ZMK_SLEEP=n

# Включаем роль центрального устройства
#CONFIG_ZMK_SPLIT_BLE_ROLE_CENTRAL=y

# Максимальное количество подключаемых половинок
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_ZMK_STUDIO=y
